### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by Ryukishi** [harshhh-dev/app-idea-generator#10]
I just read that a pull request should add at least 10 apps or 10 things, but this is not stated anywhere in the documentation of contributing or README. 
Therefore I'd like to suggest an update to state this more clearly to new users who want to contribute.

**Comment by Ryukishi** [comment]
If we don't want to update the Contributing.md then I suggest to atleast elaborate this minimum in issue #2 .

**Comment by harshhh-dev** [comment]
ok. I'll update it. Thanks for letting me know :)

**Comment by Ryukishi** [comment]
No problem!
