### ISSUE TITLE
[Feature Request] Add saving mode changes.

### ISSUE THREAD

**Issue by harshhh-dev** [harshhh-dev/app-idea-generator#6]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I reload the page and my theme choice is gone

**Describe the solution you'd like**
Save the theme in local storage.

**Comment by paulmhan** [comment]
Hey, I can work on this for you, can you assign me?

**Comment by tend2infinity** [comment]
Can I work on this issue?

**Comment by harshhh-dev** [comment]
Sorry, @tend2infinity  - Paulmhan responded first. 

if you want, you can add some more themes to our site.

**Comment by harshhh-dev** [comment]
@paulmhan I've assigned you to work on this :)

**Comment by paulmhan** [comment]
Great thanks! Working on it now

**Comment by paulmhan** [comment]
Did you want the idea to stay when a user opens up the website as well? Or only when it's refreshed?

**Comment by paulmhan** [comment]
Also I noticed that on refresh, if you're on dark mode, it'll change back to light mode. I can fix that for you as well!

**Comment by harshhh-dev** [comment]
Thanks! And I wouldn't like the idea to stay if the user opens up the website.

**Comment by paulmhan** [comment]
Created a pull request for the idea save, will work on the color mode save in a bit!
